//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  galleryPage: GalleryPage;
  galleryPageConnection: GalleryPageConnection;
  about: About;
  aboutConnection: AboutConnection;
  plant: Plant;
  plantConnection: PlantConnection;
  resource: Resource;
  resourceConnection: ResourceConnection;
  gallery: Gallery;
  galleryConnection: GalleryConnection;
  faq: Faq;
  faqConnection: FaqConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryGalleryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryPageFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryPlantArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPlantConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PlantFilter>;
};


export type QueryResourceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResourceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourceFilter>;
};


export type QueryGalleryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  galleryPage?: InputMaybe<GalleryPageFilter>;
  about?: InputMaybe<AboutFilter>;
  plant?: InputMaybe<PlantFilter>;
  resource?: InputMaybe<ResourceFilter>;
  gallery?: InputMaybe<GalleryFilter>;
  faq?: InputMaybe<FaqFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | GalleryPage | About | Plant | Resource | Gallery | Faq | Folder;

export type Home = Node & Document & {
  __typename?: 'Home';
  heroTitle: Scalars['String']['output'];
  heroSubtitle: Scalars['String']['output'];
  missionStatement?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  missionStatement?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type GalleryPage = Node & Document & {
  __typename?: 'GalleryPage';
  bannerHeading: Scalars['String']['output'];
  bannerBody?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleryPageFilter = {
  bannerHeading?: InputMaybe<StringFilter>;
  bannerBody?: InputMaybe<StringFilter>;
};

export type GalleryPageConnectionEdges = {
  __typename?: 'GalleryPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<GalleryPage>;
};

export type GalleryPageConnection = Connection & {
  __typename?: 'GalleryPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryPageConnectionEdges>>>;
};

export type AboutMissionPoints = {
  __typename?: 'AboutMissionPoints';
  emoji?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  pageTitle?: Maybe<Scalars['String']['output']>;
  pageSubtitle?: Maybe<Scalars['String']['output']>;
  storyTitle?: Maybe<Scalars['String']['output']>;
  storyContent?: Maybe<Scalars['JSON']['output']>;
  profileImage?: Maybe<Scalars['String']['output']>;
  profileCaption?: Maybe<Scalars['String']['output']>;
  missionIntro?: Maybe<Scalars['String']['output']>;
  missionPoints?: Maybe<Array<Maybe<AboutMissionPoints>>>;
  rebelSectionContent?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AboutMissionPointsFilter = {
  emoji?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  pageSubtitle?: InputMaybe<StringFilter>;
  storyTitle?: InputMaybe<StringFilter>;
  storyContent?: InputMaybe<RichTextFilter>;
  profileImage?: InputMaybe<ImageFilter>;
  profileCaption?: InputMaybe<StringFilter>;
  missionIntro?: InputMaybe<StringFilter>;
  missionPoints?: InputMaybe<AboutMissionPointsFilter>;
  rebelSectionContent?: InputMaybe<StringFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Plant = Node & Document & {
  __typename?: 'Plant';
  name: Scalars['String']['output'];
  scientificName: Scalars['String']['output'];
  description: Scalars['String']['output'];
  benefits?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PlantFilter = {
  name?: InputMaybe<StringFilter>;
  scientificName?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  benefits?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type PlantConnectionEdges = {
  __typename?: 'PlantConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Plant>;
};

export type PlantConnection = Connection & {
  __typename?: 'PlantConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PlantConnectionEdges>>>;
};

export type Resource = Node & Document & {
  __typename?: 'Resource';
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ResourceFilter = {
  title?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ResourceConnectionEdges = {
  __typename?: 'ResourceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Resource>;
};

export type ResourceConnection = Connection & {
  __typename?: 'ResourceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResourceConnectionEdges>>>;
};

export type Gallery = Node & Document & {
  __typename?: 'Gallery';
  caption: Scalars['String']['output'];
  image: Scalars['String']['output'];
  alt?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleryFilter = {
  caption?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type GalleryConnectionEdges = {
  __typename?: 'GalleryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Gallery>;
};

export type GalleryConnection = Connection & {
  __typename?: 'GalleryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryConnectionEdges>>>;
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateGalleryPage: GalleryPage;
  createGalleryPage: GalleryPage;
  updateAbout: About;
  createAbout: About;
  updatePlant: Plant;
  createPlant: Plant;
  updateResource: Resource;
  createResource: Resource;
  updateGallery: Gallery;
  createGallery: Gallery;
  updateFaq: Faq;
  createFaq: Faq;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateGalleryPageArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryPageMutation;
};


export type MutationCreateGalleryPageArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryPageMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdatePlantArgs = {
  relativePath: Scalars['String']['input'];
  params: PlantMutation;
};


export type MutationCreatePlantArgs = {
  relativePath: Scalars['String']['input'];
  params: PlantMutation;
};


export type MutationUpdateResourceArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourceMutation;
};


export type MutationCreateResourceArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourceMutation;
};


export type MutationUpdateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationCreateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  galleryPage?: InputMaybe<GalleryPageMutation>;
  about?: InputMaybe<AboutMutation>;
  plant?: InputMaybe<PlantMutation>;
  resource?: InputMaybe<ResourceMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  faq?: InputMaybe<FaqMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  galleryPage?: InputMaybe<GalleryPageMutation>;
  about?: InputMaybe<AboutMutation>;
  plant?: InputMaybe<PlantMutation>;
  resource?: InputMaybe<ResourceMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  faq?: InputMaybe<FaqMutation>;
};

export type HomeMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  missionStatement?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryPageMutation = {
  bannerHeading?: InputMaybe<Scalars['String']['input']>;
  bannerBody?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMissionPointsMutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  pageSubtitle?: InputMaybe<Scalars['String']['input']>;
  storyTitle?: InputMaybe<Scalars['String']['input']>;
  storyContent?: InputMaybe<Scalars['JSON']['input']>;
  profileImage?: InputMaybe<Scalars['String']['input']>;
  profileCaption?: InputMaybe<Scalars['String']['input']>;
  missionIntro?: InputMaybe<Scalars['String']['input']>;
  missionPoints?: InputMaybe<Array<InputMaybe<AboutMissionPointsMutation>>>;
  rebelSectionContent?: InputMaybe<Scalars['String']['input']>;
};

export type PlantMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  scientificName?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  benefits?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ResourceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryMutation = {
  caption?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type FaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', heroTitle: string, heroSubtitle: string, missionStatement?: string | null };

export type GalleryPagePartsFragment = { __typename: 'GalleryPage', bannerHeading: string, bannerBody?: string | null };

export type AboutPartsFragment = { __typename: 'About', pageTitle?: string | null, pageSubtitle?: string | null, storyTitle?: string | null, storyContent?: any | null, profileImage?: string | null, profileCaption?: string | null, missionIntro?: string | null, rebelSectionContent?: string | null, missionPoints?: Array<{ __typename: 'AboutMissionPoints', emoji?: string | null, text?: string | null } | null> | null };

export type PlantPartsFragment = { __typename: 'Plant', name: string, scientificName: string, description: string, benefits?: Array<string | null> | null, image?: string | null };

export type ResourcePartsFragment = { __typename: 'Resource', title: string, url: string, description?: string | null };

export type GalleryPartsFragment = { __typename: 'Gallery', caption: string, image: string, alt?: string | null };

export type FaqPartsFragment = { __typename: 'Faq', question: string, answer: string };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, heroTitle: string, heroSubtitle: string, missionStatement?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, heroTitle: string, heroSubtitle: string, missionStatement?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GalleryPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleryPageQuery = { __typename?: 'Query', galleryPage: { __typename: 'GalleryPage', id: string, bannerHeading: string, bannerBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GalleryPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryPageFilter>;
}>;


export type GalleryPageConnectionQuery = { __typename?: 'Query', galleryPageConnection: { __typename?: 'GalleryPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleryPageConnectionEdges', cursor: string, node?: { __typename: 'GalleryPage', id: string, bannerHeading: string, bannerBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, pageTitle?: string | null, pageSubtitle?: string | null, storyTitle?: string | null, storyContent?: any | null, profileImage?: string | null, profileCaption?: string | null, missionIntro?: string | null, rebelSectionContent?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, missionPoints?: Array<{ __typename: 'AboutMissionPoints', emoji?: string | null, text?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, pageTitle?: string | null, pageSubtitle?: string | null, storyTitle?: string | null, storyContent?: any | null, profileImage?: string | null, profileCaption?: string | null, missionIntro?: string | null, rebelSectionContent?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, missionPoints?: Array<{ __typename: 'AboutMissionPoints', emoji?: string | null, text?: string | null } | null> | null } | null } | null> | null } };

export type PlantQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PlantQuery = { __typename?: 'Query', plant: { __typename: 'Plant', id: string, name: string, scientificName: string, description: string, benefits?: Array<string | null> | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PlantConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PlantFilter>;
}>;


export type PlantConnectionQuery = { __typename?: 'Query', plantConnection: { __typename?: 'PlantConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PlantConnectionEdges', cursor: string, node?: { __typename: 'Plant', id: string, name: string, scientificName: string, description: string, benefits?: Array<string | null> | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ResourceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResourceQuery = { __typename?: 'Query', resource: { __typename: 'Resource', id: string, title: string, url: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResourceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourceFilter>;
}>;


export type ResourceConnectionQuery = { __typename?: 'Query', resourceConnection: { __typename?: 'ResourceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResourceConnectionEdges', cursor: string, node?: { __typename: 'Resource', id: string, title: string, url: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GalleryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleryQuery = { __typename?: 'Query', gallery: { __typename: 'Gallery', id: string, caption: string, image: string, alt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GalleryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
}>;


export type GalleryConnectionQuery = { __typename?: 'Query', galleryConnection: { __typename?: 'GalleryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleryConnectionEdges', cursor: string, node?: { __typename: 'Gallery', id: string, caption: string, image: string, alt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqQuery = { __typename?: 'Query', faq: { __typename: 'Faq', id: string, question: string, answer: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FaqConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
}>;


export type FaqConnectionQuery = { __typename?: 'Query', faqConnection: { __typename?: 'FaqConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqConnectionEdges', cursor: string, node?: { __typename: 'Faq', id: string, question: string, answer: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  heroTitle
  heroSubtitle
  missionStatement
}
    `;
export const GalleryPagePartsFragmentDoc = gql`
    fragment GalleryPageParts on GalleryPage {
  __typename
  bannerHeading
  bannerBody
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  pageTitle
  pageSubtitle
  storyTitle
  storyContent
  profileImage
  profileCaption
  missionIntro
  missionPoints {
    __typename
    emoji
    text
  }
  rebelSectionContent
}
    `;
export const PlantPartsFragmentDoc = gql`
    fragment PlantParts on Plant {
  __typename
  name
  scientificName
  description
  benefits
  image
}
    `;
export const ResourcePartsFragmentDoc = gql`
    fragment ResourceParts on Resource {
  __typename
  title
  url
  description
}
    `;
export const GalleryPartsFragmentDoc = gql`
    fragment GalleryParts on Gallery {
  __typename
  caption
  image
  alt
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  question
  answer
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const GalleryPageDocument = gql`
    query galleryPage($relativePath: String!) {
  galleryPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryPageParts
  }
}
    ${GalleryPagePartsFragmentDoc}`;
export const GalleryPageConnectionDocument = gql`
    query galleryPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryPageFilter) {
  galleryPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryPageParts
      }
    }
  }
}
    ${GalleryPagePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const PlantDocument = gql`
    query plant($relativePath: String!) {
  plant(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PlantParts
  }
}
    ${PlantPartsFragmentDoc}`;
export const PlantConnectionDocument = gql`
    query plantConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PlantFilter) {
  plantConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PlantParts
      }
    }
  }
}
    ${PlantPartsFragmentDoc}`;
export const ResourceDocument = gql`
    query resource($relativePath: String!) {
  resource(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResourceParts
  }
}
    ${ResourcePartsFragmentDoc}`;
export const ResourceConnectionDocument = gql`
    query resourceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResourceFilter) {
  resourceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResourceParts
      }
    }
  }
}
    ${ResourcePartsFragmentDoc}`;
export const GalleryDocument = gql`
    query gallery($relativePath: String!) {
  gallery(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryParts
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GalleryConnectionDocument = gql`
    query galleryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryFilter) {
  galleryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryParts
      }
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    galleryPage(variables: GalleryPageQueryVariables, options?: C): Promise<{data: GalleryPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageQueryVariables, query: string}> {
        return requester<{data: GalleryPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageQueryVariables, query: string}, GalleryPageQueryVariables>(GalleryPageDocument, variables, options);
      },
    galleryPageConnection(variables?: GalleryPageConnectionQueryVariables, options?: C): Promise<{data: GalleryPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageConnectionQueryVariables, query: string}, GalleryPageConnectionQueryVariables>(GalleryPageConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    plant(variables: PlantQueryVariables, options?: C): Promise<{data: PlantQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlantQueryVariables, query: string}> {
        return requester<{data: PlantQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlantQueryVariables, query: string}, PlantQueryVariables>(PlantDocument, variables, options);
      },
    plantConnection(variables?: PlantConnectionQueryVariables, options?: C): Promise<{data: PlantConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlantConnectionQueryVariables, query: string}> {
        return requester<{data: PlantConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PlantConnectionQueryVariables, query: string}, PlantConnectionQueryVariables>(PlantConnectionDocument, variables, options);
      },
    resource(variables: ResourceQueryVariables, options?: C): Promise<{data: ResourceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceQueryVariables, query: string}> {
        return requester<{data: ResourceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceQueryVariables, query: string}, ResourceQueryVariables>(ResourceDocument, variables, options);
      },
    resourceConnection(variables?: ResourceConnectionQueryVariables, options?: C): Promise<{data: ResourceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceConnectionQueryVariables, query: string}> {
        return requester<{data: ResourceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceConnectionQueryVariables, query: string}, ResourceConnectionQueryVariables>(ResourceConnectionDocument, variables, options);
      },
    gallery(variables: GalleryQueryVariables, options?: C): Promise<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}> {
        return requester<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}, GalleryQueryVariables>(GalleryDocument, variables, options);
      },
    galleryConnection(variables?: GalleryConnectionQueryVariables, options?: C): Promise<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}, GalleryConnectionQueryVariables>(GalleryConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  